
# cat(paste(sprintf("library(%s)\n", sort(unique(renv::dependencies()$Package))), collapse = ""))
library(bdc)
library(bslib)
library(cli)
library(ConR)
library(ConApp)
library(crosstalk)
library(datamods)
library(DBI)
library(dplyr)
library(esquisse)
library(ggplot2)
library(glue)
library(grDevices)
library(htmltools)
library(jsonlite)
library(kableExtra)
library(knitr)
library(leaflet)
library(leafpm)
library(measurements)
library(phosphoricons)
library(pkgload)
library(raster)
library(reactable)
library(rgbif)
library(rio)
library(rmarkdown)
library(RPostgres)
library(rsconnect)
library(sf)
library(shiny)
library(shinybusy)
library(shinyjs)
library(shinyWidgets)
library(stats)
library(taxize)
library(terra)
library(tibble)
library(tidyr)
library(tidyselect)
library(utils)
library(validate)
library(lwgeom)

# remotes::install_github("dreamRs/ConApp")
library(ConApp)


shiny::shinyApp(
  ui = conr_ui(),
  server = conr_server()
)

