
library(ConR) # remotes::install_github("gdauby/ConR")
library(ConApp) # remotes::install_github("gdauby/ConApp", upgrade = FALSE)

# BiocManager::install("BiocVersion")
library(shiny)
library(rsconnect)
library(pkgload)
library(shiny)
library(bdc)
library(bslib)
library(cli)
library(datamods)
library(DBI)
library(dplyr)
library(esquisse)
library(glue)
library(htmltools)
library(jsonlite)
library(kableExtra)
library(leaflet)
library(leafpm)
library(measurements)
library(phosphoricons)
library(reactable)
library(rgbif)
library(rmarkdown)
library(RPostgres)
library(sf)
library(shinybusy)
library(shinyjs)
library(shinyWidgets)
library(jsonlite)
library(taxize)
library(terra)
library(tibble)
library(tidyr)
library(tidyselect)
library(validate)
library(crosstalk)
library(ggplot2)
library(raster)
library(rio)
library(knitr)
library(grDevices)
library(stats)
library(utils)
library(rnaturalearth)
library(lwgeom)

shiny::shinyApp(
  ui = conr_ui(),
  server = conr_server()
)

